In [29]:
#Начнём с поиска дубликатов в данных. Найдите все повторяющиеся строки в данных и удалите их. 
# Для поиска используйте все признаки в данных. Сколько записей осталось в данных?
#Далее найдите все неинформативные признаки в данных и избавьтесь от них. 
# В качестве порога информативности возьмите 0.95: удалите все признаки, для которых 95 % 
# значений повторяются или 95 % записей уникальны. В ответ запишите имена признаков, которые вы нашли (без кавычек).
#Примечание: дальнейшая работа производится с очищенными от дубликатов и неинформативных признаков данных.
import pandas as pd
di = pd.read_csv('diabetes_data.csv')
display(di.head())
di = di.drop_duplicates()
di.shape[0]
low_information_cols = [] 

#цикл по всем столбцам
for col in di.columns:
    #наибольшая относительная частота в признаке
    top_freq = di[col].value_counts(normalize=True).max()
    #доля уникальных значений от размера признака
    nunique_ratio = di[col].nunique() / di[col].count()
    # сравниваем наибольшую частоту с порогом
    if top_freq > 0.95:
        low_information_cols.append(col)
        print(f'{col}: {round(top_freq*100, 2)}% одинаковых значений')
    # сравниваем долю уникальных значений с порогом
    if nunique_ratio > 0.95:
        low_information_cols.append(col)
        print(f'{col}: {round(nunique_ratio*100, 2)}% уникальных значений')

print(low_information_cols)
di = di.drop(low_information_cols, axis=1)
print(f'Результирующее число признаков: {di.shape[1]}')
cols_null_percent = di.isnull().mean() * 100
cols_with_null = cols_null_percent[cols_null_percent>0].sort_values(ascending=False)
display(cols_with_null)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Gender
0,6,98,58,33,190,34.0,0.430,43,0,Female
1,2,112,75,32,0,35.7,0.148,21,0,Female
2,2,108,64,0,0,30.8,0.158,21,0,Female
3,8,107,80,0,0,24.6,0.856,34,0,Female
4,7,136,90,0,0,29.9,0.210,50,0,Female

Gender: 100.0% одинаковых значений
['Gender']
Результирующее число признаков: 9

Series([], dtype: float64)

In [30]:

#Попробуйте найти пропуски в данных с помощью метода isnull().

#Спойлер: ничего не найдёте. А они есть! Просто они скрыты от наших глаз. 
# В таблице пропуски в столбцах Glucose, BloodPressure, SkinThickness, Insulin и BMI 
# обозначены нулём, поэтому традиционные методы поиска пропусков ничего вам не покажут. Давайте это исправим!

#Замените все записи, равные 0, в столбцах Glucose, BloodPressure, SkinThickness, Insulin и BMI 
# на символ пропуска. Его вы можете взять из библиотеки numpy: np.nan.

#Какая доля пропусков содержится в столбце Insulin? Ответ округлите до сотых.

import numpy as np
a = lambda x: np.nan if x == 0 else x
for b in di[['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']]:
    di[b] = di[b].apply(a)
display(di['Insulin'].isnull().mean())

0.4869791666666667

In [31]:
#Удалите из данных признаки, где число пропусков составляет более 30 %.
#  Сколько признаков осталось в ваших данных (с учетом удаленных неинформативных признаков в задании 8.2)?
thresh = di.shape[0]*0.7
#удаляем столбцы, в которых более 30% (100-70) пропусков
di = di.dropna(thresh=thresh, axis=1)
display(di)
display(di.shape)

,Pregnancies,Glucose,BloodPressure,SkinThickness,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,98.0,58.0,33.0,34.0,0.430,43,0
1,2,112.0,75.0,32.0,35.7,0.148,21,0
2,2,108.0,64.0,NaN,30.8,0.158,21,0
3,8,107.0,80.0,NaN,24.6,0.856,34,0
4,7,136.0,90.0,NaN,29.9,0.210,50,0
...,...,...,...,...,...,...,...,...
763,5,139.0,64.0,35.0,28.6,0.411,26,0
764,1,96.0,122.0,NaN,22.4,0.207,27,0
765,10,101.0,86.0,37.0,45.6,1.136,38,1
766,0,141.0,NaN,NaN,42.4,0.205,29,1
767,0,125.0,96.0,NaN,22.5,0.262,21,0

(768, 8)

In [32]:
#Удалите из данных только те строки, в которых содержится более двух пропусков одновременно.
#  Чему равно результирующее число записей в таблице?
thresh2 = di.shape[1] - 2
di = di.dropna(thresh=thresh2, axis=0)
display(di)
display(di.shape)

,Pregnancies,Glucose,BloodPressure,SkinThickness,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,98.0,58.0,33.0,34.0,0.430,43,0
1,2,112.0,75.0,32.0,35.7,0.148,21,0
2,2,108.0,64.0,NaN,30.8,0.158,21,0
3,8,107.0,80.0,NaN,24.6,0.856,34,0
4,7,136.0,90.0,NaN,29.9,0.210,50,0
...,...,...,...,...,...,...,...,...
763,5,139.0,64.0,35.0,28.6,0.411,26,0
764,1,96.0,122.0,NaN,22.4,0.207,27,0
765,10,101.0,86.0,37.0,45.6,1.136,38,1
766,0,141.0,NaN,NaN,42.4,0.205,29,1
767,0,125.0,96.0,NaN,22.5,0.262,21,0

(761, 8)

In [34]:
#В оставшихся записях замените пропуски на медиану.
#  Чему равно среднее значение в столбце SkinThickness? Ответ округлите до десятых.
values = {
    'Pregnancies': di['Pregnancies'].median(),
    'Glucose': di['Glucose'].median(),
    'BloodPressure': di['BloodPressure'].median(),
    'SkinThickness': di['SkinThickness'].median(),
    'BMI': di['BMI'].median(),
    'DiabetesPedigreeFunction': di['DiabetesPedigreeFunction'].median(),
    'Age': di['Age'].median(),
}
#заполняем пропуски в соответствии с заявленным словарем
di = di.fillna(values)
display(di)
display(di['SkinThickness'].mean())

,Pregnancies,Glucose,BloodPressure,SkinThickness,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,98.0,58.0,33.0,34.0,0.430,43,0
1,2,112.0,75.0,32.0,35.7,0.148,21,0
2,2,108.0,64.0,29.0,30.8,0.158,21,0
3,8,107.0,80.0,29.0,24.6,0.856,34,0
4,7,136.0,90.0,29.0,29.9,0.210,50,0
...,...,...,...,...,...,...,...,...
763,5,139.0,64.0,35.0,28.6,0.411,26,0
764,1,96.0,122.0,29.0,22.4,0.207,27,0
765,10,101.0,86.0,37.0,45.6,1.136,38,1
766,0,141.0,72.0,29.0,42.4,0.205,29,1
767,0,125.0,96.0,29.0,22.5,0.262,21,0

29.109067017082786

In [36]:
#Сколько выбросов найдёт классический метод межквартильного размаха в признаке SkinThickness?
def outliers_iqr(data, feature):
    x = data[feature]
    quartile_1, quartile_3 = x.quantile(0.25), x.quantile(0.75),
    iqr = quartile_3 - quartile_1
    lower_bound = quartile_1 - (iqr * 1.5)
    upper_bound = quartile_3 + (iqr * 1.5)
    outliers = data[(x<lower_bound) | (x > upper_bound)]
    cleaned = data[(x>lower_bound) & (x < upper_bound)]
    return outliers, cleaned
outliers, cleaned = outliers_iqr(di, 'SkinThickness')


print(f'Число выбросов по методу Тьюки: {outliers.shape[0]}')
print(f'Результирующее число записей: {cleaned.shape[0]}')

Число выбросов по методу Тьюки: 87
Результирующее число записей: 674

In [41]:
#Сколько выбросов найдёт классический метод z-отклонения в признаке SkinThickness?
def outliers_z_score_mod(data, feature):
    x = data[feature]
    mu = x.mean()
    sigma = x.std()
    lower_bound = mu - 3 * sigma
    upper_bound = mu + 3 * sigma
    outliers = data[(x < lower_bound) | (x > upper_bound)]
    cleaned = data[(x > lower_bound) & (x < upper_bound)]
    return outliers, cleaned

outliers, cleaned = outliers_z_score_mod(di, 'SkinThickness')

print(f'Число выбросов по методу z-отклонения: {outliers.shape[0]}')
print(f'Результирующее число записей: {cleaned.shape[0]}')


#На приведённой гистограмме показано распределение признака DiabetesPedigreeFunction. 
# Такой вид распределения очень похож на логнормальный, и он заставляет задуматься о логарифмировании признака.
#  Найдите сначала число выбросов в признаке DiabetesPedigreeFunction с помощью классического
#  метода межквартильного размаха.
#Затем найдите число выбросов в этом же признаке в логарифмическом масштабе 
# (при логарифмировании единицу прибавлять не нужно!). Какова разница между двумя этими числами (вычтите из первого второе)?



def outliers_iqr(data, feature):
    x = data[feature]
    quartile_1, quartile_3 = x.quantile(0.25), x.quantile(0.75),
    iqr = quartile_3 - quartile_1
    lower_bound = quartile_1 - (iqr * 1.5)
    upper_bound = quartile_3 + (iqr * 1.5)
    outliers = data[(x<lower_bound) | (x > upper_bound)]
    cleaned = data[(x>lower_bound) & (x < upper_bound)]
    return outliers, cleaned
outliers, cleaned = outliers_iqr(di, 'DiabetesPedigreeFunction')


print(f'Число выбросов по методу Тьюки: {outliers.shape[0]}')


def outliers_iqr_mod(data, feature, log_scale = False, left = 1.5, right= 1.5):
    if log_scale:
        x = np.log(data[feature])
    else:
        x = data[feature]
    quartile_1, quartile_3 = x.quantile(0.25), x.quantile(0.75),
    iqr = quartile_3 - quartile_1
    lower_bound = quartile_1 - (iqr *left )
    upper_bound = quartile_3 + (iqr * right)
    outliers = data[(x<lower_bound) | (x > upper_bound)]
    cleaned = data[(x>lower_bound) & (x < upper_bound)]
    return outliers, cleaned
outliers, cleaned = outliers_iqr_mod(di, 'DiabetesPedigreeFunction', True)
print(f'Число выбросов по методу Тьюки c логарифмом: {outliers.shape[0]}')

Число выбросов по методу z-отклонения: 4
Результирующее число записей: 757
Число выбросов по методу Тьюки: 29
Число выбросов по методу Тьюки c логарифмом: 0